#! /usr/bin/env bash

languages=$(echo "javascript python c cpp bash java golang rust php" | tr " " "\n")
core_utils=$(echo "find xargs sed akw" | tr " " "\n")
selected=$(echo -e "$languages\n$core_utils" | fzf)

read -p 'Query: ' query

if echo "$languages" | grep -qs $selected; then
  tmux split-window -h bash -c "curl cht.sh/$selected/$(echo "$query" | tr " " "+") | less"
else
  tmux split-window -h bash -c "curl cht.sh/$selected~$query | less"
fi

