#! /usr/bin/env bash

session=$(find ~/development -mindepth 1 -maxdepth 3 -type d | fzf)
# session=$(find ~/development/aramika ~/development/monterail ~/development/montrose ~/development/projects ~/development/learning ~/development/ra-int ~/development/recruitment-tasks ~/development/judy ~/development/jukegroup ~/development/jukesites ~/development/poc -mindepth 1 -maxdepth 2 -type d | fzf)
session_name=$(basename "$session" | tr . _)

echo $session_name
echo $session

if ! tmux has-session -t "$session_name" 2> /dev/null; then
  tmux new-session -s "$session_name" -c "$session" -d
fi

tmux switch-client -t "$session_name"
