#! /usr/bin/env bash

session=$(find ~/dev ~/mrs-dev ~/jake-dev -mindepth 1 -maxdepth 2 -type d | fzf)
session_name=$(basename "$session" | tr . _)

echo $session_name
echo $session

if ! tmux has-session -t "$session_name" 2> /dev/null; then
  tmux new-session -s "$session_name" -c "$session" -d
fi

tmux switch-client -t "$session_name"
