vim.keymap.set({ 'n', 'v' }, '<Space>', '<Nop>', { silent = true })
vim.keymap.set('n', 'k', "v:count == 0 ? 'gk' : 'k'", { expr = true, silent = true })
vim.keymap.set('n', 'j', "v:count == 0 ? 'gj' : 'j'", { expr = true, silent = true })
vim.keymap.set({ 'n', 'v' }, '<leader>t', ':Neotree toggle<CR>', { silent = true })
vim.keymap.set({ 'n', 'v' }, '<leader>t', ':Neotree toggle<CR>', { silent = true })
vim.keymap.set('n', '<leader>q', '<cmd>Bdelete<CR>')
vim.keymap.set('n', '<C-q>', '<cmd>qa!<CR>')
vim.keymap.set('n', '<leader>w', '<cmd>write<cr>', {desc = 'Save'})
vim.keymap.set('n', '<C-s>', '<cmd>EslintFixAll<cr><cmd>write<cr>', {desc = 'Save'})
vim.keymap.set('n', '<C-a>', 'ggVG')
vim.keymap.set({ 'n', 'v' }, '<C-c>', '"*y')
vim.keymap.set({ 'n', 'v' }, '<C-y>', '"+y')
vim.keymap.set({ 'n', 'v' }, '<C-l>', '"+p')
vim.keymap.set({ 'n', 'x' }, 'x', '"_x')
vim.keymap.set('n', '<C-]>', '<cmd>:bn<CR>')
vim.keymap.set('n', '<C-[>', '<cmd>:bp<CR>')
vim.keymap.set('n', '[d', vim.diagnostic.goto_prev, { desc = "Go to previous diagnostic messasge" })
vim.keymap.set('n', ']d', vim.diagnostic.goto_next, { desc = "Go to next diagnostic message" })
vim.keymap.set('n', '<leader>e', vim.diagnostic.open_float, { desc = "Open floating diagnostic[E] message" })
vim.keymap.set('n', '<leader>el', vim.diagnostic.setloclist, { desc = "Open diagnostics[E] [L]ist" })

