require("plugins.lazy")
require("plugins.treesitter")
require("plugins.neotree")
require("plugins.telescope")
require("plugins.gitsigns")
require("plugins.autocmp")
require("plugins.lsp")
require("plugins.conform")
-- require("plugins.gpt")
